import { Doctor, ServicePrice } from './types';

export const CLINIC_INFO = {
  name: 'Доктор Плюс',
  fullName: 'Многопрофильный медицинский центр Доктор Плюс',
  address: 'ул. Махатмы Ганди, 201, Бишкек, Кыргызстан',
  phone: '+996 (555) 060-601',
  whatsapp: '996555060601',
  hours: 'Пн-Сб: 08:00-18:00, Воскресенье: выходной',
  rating: 4.9,
  reviewsCount: 41,
  license: 'НГМУ-4518',
  awards: ['Лучший медцентр 2025 по версии 2GIS'],
  altegioUrl: 'https://n1220069.alteg.io/company/1166149/personal/menu?o=',
};

export const DOCTORS: Doctor[] = [
  {
    id: 'sultangazy-kyzy-nazgul',
    name: 'Султангазы кызы Назгуль',
    specialty: 'Педиатр, семейный врач',
    department: 'Педиатрия',
    rating: 5,
    reviewCount: 27,
    photoUrl: '/doctors/sultangazy-kyzy-nazgul.webp',
    schedule: 'Пн-Сб: 08:30 - 17:00',
    education: 'Кыргызская государственная медицинская академия им. И.К. Ахунбаева. Специализация: педиатрия и семейная медицина.',
    reviews: [
      { author: 'Айбек', text: 'Очень грамотный врач, быстро находит подход к детям и подробно объясняет лечение.' },
      { author: 'Мээрим', text: 'Ходим к ней всей семьей. Внимательная, спокойная и очень профессиональная.' },
    ],
  },
  {
    id: 'kabulova-gulbara-saparalievna',
    name: 'Кабулова Гулбара Сапаралиевна',
    specialty: 'Кардиолог, УЗИ-специалист',
    department: 'Кардиология',
    rating: 5,
    reviewCount: 5,
    photoUrl: '/doctors/kabulova-gulbara-saparalievna.webp',
    schedule: 'Пн-Пт: 09:00 - 16:00',
    education: 'Отличник здравоохранения КР. Специализируется на кардиологии и ультразвуковой диагностике.',
    reviews: [{ author: 'Анна', text: 'Делала УЗИ сердца. Все было спокойно, аккуратно и очень понятно.' }],
  },
  {
    id: 'moldosheva-gulzat-sharshebaevna',
    name: 'Молдошева Гулзат Шаршебаевна',
    specialty: 'Терапевт, УЗИ-специалист',
    department: 'Терапия',
    rating: 4.9,
    reviewCount: 6,
    photoUrl: '/doctors/moldosheva-gulzat-sharshebaevna.webp',
    schedule: 'Пн-Сб: 10:00 - 18:00',
    education: 'КГМА, семейная медицина и терапия. Специализируется на комплексной диагностике внутренних органов.',
    reviews: [{ author: 'Бакыт', text: 'Внимательный терапевт, назначила понятное и эффективное лечение без лишних анализов.' }],
  },
  {
    id: 'kabylov-zhyldyzbek-saparovich',
    name: 'Кабылов Жылдызбек Сапарович',
    specialty: 'Плазмаферез, эфферентная терапия',
    department: 'Плазмаферез',
    rating: 5,
    reviewCount: 2,
    photoUrl: '/doctors/kabylov-zhyldyzbek-saparovich.jpeg',
    schedule: 'По записи',
    education: 'Специалист по эфферентным методам терапии и медицинским процедурам.',
    reviews: [{ author: 'Игорь', text: 'Проходил курс процедур, все было организовано четко и профессионально.' }],
  },
];

export const PRICES: ServicePrice[] = [
  {
    id: 'consult-therapist',
    name: 'Консультация терапевта',
    price: '900 сом',
    category: 'Консультации',
    department: 'Терапия',
    description: 'Первичный прием, осмотр, рекомендации и план обследования.',
    duration: '30-40 мин',
    doctorIds: ['moldosheva-gulzat-sharshebaevna'],
    badge: 'Популярно',
    bookable: true,
  },
  {
    id: 'consult-pediatrician',
    name: 'Консультация педиатра',
    price: '900 сом',
    category: 'Консультации',
    department: 'Педиатрия',
    description: 'Осмотр ребенка, рекомендации по лечению и наблюдению.',
    duration: '30 мин',
    doctorIds: ['sultangazy-kyzy-nazgul'],
    badge: 'Детям',
    bookable: true,
  },
  {
    id: 'consult-cardiologist',
    name: 'Консультация кардиолога',
    price: '1200 сом',
    category: 'Консультации',
    department: 'Кардиология',
    description: 'Прием кардиолога с оценкой жалоб и подбором дальнейшей диагностики.',
    duration: '40 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    badge: 'Сердце',
    bookable: true,
  },
  {
    id: 'consult-repeat',
    name: 'Повторная консультация',
    price: '700 сом',
    category: 'Консультации',
    department: 'Терапия',
    description: 'Контроль лечения, динамика состояния и коррекция назначений.',
    duration: '20 мин',
    doctorIds: ['moldosheva-gulzat-sharshebaevna', 'sultangazy-kyzy-nazgul', 'kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'uzi-abdomen',
    name: 'УЗИ брюшной полости',
    price: '1200 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Печень, желчный пузырь, поджелудочная железа, селезенка.',
    duration: '25 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    badge: 'Диагностика',
    bookable: true,
  },
  {
    id: 'uzi-kidney',
    name: 'УЗИ почек и мочевого пузыря',
    price: '800 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Оценка почек, мочеточников и остаточной мочи.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'uzi-thyroid',
    name: 'УЗИ щитовидной железы',
    price: '700 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Проверка структуры железы, узлов и объема.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'uzi-pelvis',
    name: 'УЗИ органов малого таза',
    price: '1000 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Диагностика малого таза по назначению врача.',
    duration: '20-25 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'uzi-heart',
    name: 'УЗИ сердца (ЭхоКГ)',
    price: '1500 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Эхокардиография для оценки клапанов, камер и сократимости сердца.',
    duration: '30 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    badge: 'Премиум',
    bookable: true,
  },
  {
    id: 'uzi-vessels',
    name: 'УЗИ сосудов',
    price: '1400 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Исследование кровотока и состояния сосудистой стенки.',
    duration: '30 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'uzi-breast',
    name: 'УЗИ молочных желез',
    price: '1000 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Профилактическая и диагностическая оценка тканей молочных желез.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'uzi-soft-tissues',
    name: 'УЗИ мягких тканей',
    price: '900 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Исследование мягких тканей, лимфоузлов и локальных образований.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'uzi-pregnancy',
    name: 'УЗИ при беременности',
    price: '1200 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Контрольное ультразвуковое исследование по сроку беременности.',
    duration: '20-30 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    badge: 'Популярно',
    bookable: true,
  },
  {
    id: 'ecg-basic',
    name: 'ЭКГ с расшифровкой',
    price: '500 сом',
    category: 'ЭКГ',
    department: 'Кардиология',
    description: 'Электрокардиограмма с заключением врача.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'ecg-load',
    name: 'ЭКГ контрольное исследование',
    price: '600 сом',
    category: 'ЭКГ',
    department: 'Кардиология',
    description: 'Повторная регистрация ЭКГ в динамике лечения.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
  {
    id: 'lab-cbc',
    name: 'Общий анализ крови',
    price: '400 сом',
    category: 'Лаборатория',
    department: 'Терапия',
    description: 'Базовый клинический анализ крови.',
    duration: 'По регистратуре',
    badge: 'Через регистратуру',
    bookable: false,
  },
  {
    id: 'lab-urine',
    name: 'Общий анализ мочи',
    price: '250 сом',
    category: 'Лаборатория',
    department: 'Терапия',
    description: 'Стандартное исследование мочи.',
    duration: 'По регистратуре',
    bookable: false,
  },
  {
    id: 'lab-biochem',
    name: 'Биохимический анализ крови',
    price: 'от 1200 сом',
    category: 'Лаборатория',
    department: 'Терапия',
    description: 'Печеночные, почечные и метаболические показатели.',
    duration: 'По регистратуре',
    badge: 'Комплекс',
    bookable: false,
  },
  {
    id: 'lab-thyroid',
    name: 'Гормоны щитовидной железы',
    price: 'от 1600 сом',
    category: 'Лаборатория',
    department: 'Терапия',
    description: 'ТТГ, Т3, Т4 и дополнительные панели по показаниям.',
    duration: 'По регистратуре',
    bookable: false,
  },
  {
    id: 'lab-lipid',
    name: 'Липидный профиль',
    price: '850 сом',
    category: 'Лаборатория',
    department: 'Кардиология',
    description: 'Холестерин, ЛПНП, ЛПВП, триглицериды.',
    duration: 'По регистратуре',
    bookable: false,
  },
  {
    id: 'procedure-iv',
    name: 'Внутривенная капельница',
    price: '400 сом',
    category: 'Процедуры',
    department: 'Терапия',
    description: 'Процедура по назначению врача.',
    duration: '30-60 мин',
    doctorIds: ['moldosheva-gulzat-sharshebaevna'],
    badge: 'Процедура',
    bookable: true,
  },
  {
    id: 'procedure-im',
    name: 'Внутримышечный укол',
    price: '150 сом',
    category: 'Процедуры',
    department: 'Терапия',
    description: 'Инъекция по направлению врача.',
    duration: '10 мин',
    doctorIds: ['moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'procedure-iv-shot',
    name: 'Внутривенная инъекция',
    price: '250 сом',
    category: 'Процедуры',
    department: 'Терапия',
    description: 'Введение препаратов внутривенно.',
    duration: '15 мин',
    doctorIds: ['moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'plasma-session',
    name: 'Плазмаферез (1 сеанс)',
    price: 'Уточняйте',
    category: 'Плазмаферез',
    department: 'Плазмаферез',
    description: 'Эфферентная процедура по индивидуальному протоколу.',
    duration: '60-90 мин',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    badge: 'По назначению',
    bookable: true,
  },
  {
    id: 'plasma-consult',
    name: 'Консультация по плазмаферезу',
    price: '1200 сом',
    category: 'Плазмаферез',
    department: 'Плазмаферез',
    description: 'Оценка показаний, противопоказаний и плана курса.',
    duration: '30 мин',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    bookable: true,
  },
  {
    id: 'special-vlok',
    name: 'ВЛОК',
    price: 'Уточняйте',
    category: 'Спецпроцедуры',
    department: 'Плазмаферез',
    description: 'Внутривенное лазерное облучение крови по показаниям.',
    duration: 'По назначению',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    badge: 'Спецпроцедура',
    bookable: true,
  },
  {
    id: 'special-detox',
    name: 'Индивидуальная детокс-программа',
    price: 'Уточняйте',
    category: 'Спецпроцедуры',
    department: 'Плазмаферез',
    description: 'Комплексная программа под наблюдением специалиста.',
    duration: 'Индивидуально',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    bookable: true,
  },
];
