import { Doctor, ServicePrice } from './types';

export const CLINIC_INFO = {
  name: 'Доктор Плюс',
  fullName: 'Многопрофильный медицинский центр Доктор Плюс',
  address: 'ул. Махатмы Ганди, 201, Бишкек, Кыргызстан',
  phone: '+996 (702) 018-112',
  whatsapp: '996702018112',
  hours: 'Пн-Сб: 08:00-18:00, Воскресенье: выходной',
  rating: 4.9,
  reviewsCount: 41,
  license: 'НГМУ-4518',
  awards: ['Лучший медцентр 2025 по версии 2GIS'],
  altegioUrl: 'https://n1220069.alteg.io/company/1166149/personal/menu?o=',
};

export const DOCTORS: Doctor[] = [
  {
    id: 'sultangazy-kyzy-nazgul',
    name: 'Султангазы кызы Назгуль',
    specialty: 'Педиатр, семейный врач',
    department: 'Педиатрия',
    rating: 5,
    reviewCount: 27,
    photoUrl: '/doctors/sultangazy-kyzy-nazgul.webp',
    schedule: 'Пн-Сб: 08:30 - 17:00',
    education: 'Кыргызская государственная медицинская академия им. И.К. Ахунбаева. Специализация: педиатрия и семейная медицина.',
    reviews: [
      { author: 'Айбек', text: 'Очень грамотный врач, быстро находит подход к детям и подробно объясняет лечение.' },
      { author: 'Мээрим', text: 'Ходим к ней всей семьей. Внимательная, спокойная и очень профессиональная.' },
    ],
  },
  {
    id: 'kabulova-gulbara-saparalievna',
    name: 'Кабулова Гулбара Сапаралиевна',
    specialty: 'Кардиолог, УЗИ-специалист',
    department: 'Кардиология',
    rating: 5,
    reviewCount: 5,
    photoUrl: '/doctors/kabulova-gulbara-saparalievna.webp',
    schedule: 'Пн-Пт: 09:00 - 16:00',
    education: 'Отличник здравоохранения КР. Специализируется на кардиологии и ультразвуковой диагностике.',
    reviews: [{ author: 'Анна', text: 'Делала УЗИ сердца. Все было спокойно, аккуратно и очень понятно.' }],
  },
  {
    id: 'moldosheva-gulzat-sharshebaevna',
    name: 'Молдошева Гулзат Шаршебаевна',
    specialty: 'Терапевт, УЗИ-специалист',
    department: 'Терапия',
    rating: 4.9,
    reviewCount: 6,
    photoUrl: '/doctors/moldosheva-gulzat-sharshebaevna.webp',
    schedule: 'Сб: 10:00 - 16:00',
    education: 'КГМА, семейная медицина и терапия. Специализируется на комплексной диагностике внутренних органов.',
    reviews: [{ author: 'Бакыт', text: 'Внимательный терапевт, назначила понятное и эффективное лечение без лишних анализов.' }],
  },
  {
    id: 'kabylov-zhyldyzbek-saparovich',
    name: 'Кабылов Жылдызбек Сапарович',
    specialty: 'Плазмаферез, эфферентная терапия',
    department: 'Плазмаферез',
    rating: 5,
    reviewCount: 2,
    photoUrl: '/doctors/kabylov-zhyldyzbek-saparovich.jpeg',
    schedule: 'По записи',
    education: 'Специалист по эфферентным методам терапии и медицинским процедурам.',
    reviews: [{ author: 'Игорь', text: 'Проходил курс процедур, все было организовано четко и профессионально.' }],
  },
  {
    id: 'procedure-room',
    name: 'Процедурный кабинет',
    specialty: 'Медсестринские процедуры',
    department: 'Процедурный кабинет',
    rating: 5,
    reviewCount: 0,
    photoUrl: '/doctors/procedure-room.svg',
    schedule: 'Пн-Сб: 08:00 - 18:00',
    education: 'Капельницы, внутривенные и внутримышечные процедуры выполняются медперсоналом по назначению врача.',
    reviews: [],
  },
  {
    id: 'logoped-room',
    name: 'Кабылова Саикал',
    specialty: 'Логопед-дефектолог',
    department: 'Логопед-дефектолог',
    rating: 5,
    reviewCount: 0,
    photoUrl: '/doctors/logoped-room.svg',
    schedule: 'Ср, Пт: 11:00 - 16:30',
    education: 'Консультации, индивидуальные занятия и логопедический массаж для детей и взрослых.',
    reviews: [],
  },
  {
    id: 'tolkun-abdysultanovna-esenova',
    name: 'Толкун Абдысултановна Эсенова',
    specialty: 'Гинеколог',
    department: 'Гинекология',
    rating: 5,
    reviewCount: 0,
    photoUrl: '/doctors/tolkun-abdysultanovna-esenova.svg',
    schedule: 'Пн-Сб: 13:00 - 18:00',
    education: 'Консультации гинеколога, осмотр и рекомендации по женскому здоровью.',
    reviews: [],
  },
  {
    id: 'iliyasova-zarina-sovetbekovna',
    name: 'Илиясова Зарина Советовна',
    specialty: 'Гинеколог',
    department: 'Гинекология',
    rating: 5,
    reviewCount: 0,
    photoUrl: '/doctors/iliyasova-zarina-sovetbekovna.svg',
    schedule: 'Пн-Сб: 09:00 - 13:00',
    education: 'Консультации гинеколога, профилактический осмотр и рекомендации специалиста.',
    reviews: [],
  },
  {
    id: 'mansur-nigmat',
    name: 'Мансур Нигмат',
    specialty: 'ЛОР-врач',
    department: 'ЛОР',
    rating: 5,
    reviewCount: 0,
    photoUrl: '/doctors/mansur-nigmat.svg',
    schedule: 'Пн-Сб: 09:00 - 16:00',
    education: 'Консультации ЛОР-врача по заболеваниям уха, горла и носа.',
    reviews: [],
  },
];

export const PRICES: ServicePrice[] = [
  {
    id: 'consult-primary',
    name: 'Первичный осмотр врача',
    price: '1000 сом',
    category: 'Консультации',
    department: 'Терапия',
    description: 'Первичный прием специалиста, осмотр и рекомендации.',
    duration: '30-40 мин',
    doctorIds: [
      'moldosheva-gulzat-sharshebaevna',
      'sultangazy-kyzy-nazgul',
      'kabulova-gulbara-saparalievna',
    ],
    badge: 'Прием',
    bookable: true,
  },
  {
    id: 'consult-repeat',
    name: 'Вторичный осмотр врача',
    price: '800 сом',
    category: 'Консультации',
    department: 'Терапия',
    description: 'Повторный прием для контроля лечения и динамики состояния.',
    duration: '20-30 мин',
    doctorIds: [
      'moldosheva-gulzat-sharshebaevna',
      'sultangazy-kyzy-nazgul',
      'kabulova-gulbara-saparalievna',
    ],
    bookable: true,
  },
  {
    id: 'uzi-thyroid',
    name: 'Щитовидная железа',
    price: '800 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование щитовидной железы.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-breast',
    name: 'Молочные железы',
    price: '700 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование молочных желез.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-gallbladder-function',
    name: 'Определение функции желчного пузыря',
    price: '800 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Исследование функции желчного пузыря.',
    duration: '30 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-spleen',
    name: 'Селезенка',
    price: '400 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование селезенки.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-kidneys-bladder-prostate',
    name: 'Почки, мочевой пузырь, предстательная железа',
    price: '1000 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Комплексное исследование мочевыделительной системы и предстательной железы.',
    duration: '25 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-neck-vessels',
    name: 'Сосуды шеи',
    price: '1000 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Исследование сосудов шеи и кровотока.',
    duration: '25 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-adrenal',
    name: 'Надпочечники',
    price: '450 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование надпочечников.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-liver-gallbladder',
    name: 'Печень, желчный пузырь',
    price: '700 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Исследование печени и желчного пузыря.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-pancreas',
    name: 'Поджелудочная железа',
    price: '450 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование поджелудочной железы.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-prostate',
    name: 'Предстательная железа',
    price: '500 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование предстательной железы.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-abdomen-complex',
    name: 'Общий комплекс брюшной полости',
    price: '2300 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Печень, желчный пузырь, поджелудочная железа, селезенка, почки, мочевой пузырь.',
    duration: '35 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    badge: 'Комплекс',
    bookable: true,
  },
  {
    id: 'uzi-kidneys-bladder',
    name: 'Почки + мочевой пузырь',
    price: '900 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Комплексное исследование почек и мочевого пузыря.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-kidneys',
    name: 'Почки',
    price: '700 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование почек.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-bladder',
    name: 'Мочевой пузырь',
    price: '400 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование мочевого пузыря.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-folliculometry',
    name: 'Фолликулометрия',
    price: '700 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Контроль роста фолликулов по назначению врача.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-early-pregnancy',
    name: 'Определение беременности до 6 недель',
    price: '900 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Раннее ультразвуковое определение беременности.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-pregnancy-1',
    name: 'Беременность I триместр',
    price: '1100 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'УЗИ беременности в первом триместре.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-pregnancy-2',
    name: 'Беременность II триместр',
    price: '1200 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'УЗИ беременности во втором триместре.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-pregnancy-3',
    name: 'Беременность III триместр',
    price: '1300 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'УЗИ беременности в третьем триместре.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-uterus-appendages',
    name: 'Матка и её придатки',
    price: '1000 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковое исследование матки и придатков.',
    duration: '20 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'uzi-symphysitis',
    name: 'Симфизит',
    price: '500 сом',
    category: 'УЗИ',
    department: 'УЗИ',
    description: 'Ультразвуковая оценка признаков симфизита.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna', 'moldosheva-gulzat-sharshebaevna'],
    bookable: true,
  },
  {
    id: 'efferent-plasma',
    name: 'Плазмаферез',
    price: '5000 сом',
    category: 'Эфферентология',
    department: 'Плазмаферез',
    description: 'Эфферентная процедура по назначению специалиста.',
    duration: '60-90 мин',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    bookable: true,
  },
  {
    id: 'gynecology-consult',
    name: 'Консультация гинеколога',
    price: 'Уточнить',
    category: 'Гинекология',
    department: 'Гинекология',
    description: 'Прием гинеколога, осмотр и рекомендации специалиста.',
    duration: '30 мин',
    doctorIds: ['tolkun-abdysultanovna-esenova', 'iliyasova-zarina-sovetbekovna'],
    badge: 'Прием',
    bookable: true,
  },
  {
    id: 'lor-consult',
    name: 'Консультация ЛОР-врача',
    price: 'Уточнить',
    category: 'ЛОР',
    department: 'ЛОР',
    description: 'Прием специалиста по заболеваниям уха, горла и носа.',
    duration: '30 мин',
    doctorIds: ['mansur-nigmat'],
    badge: 'Прием',
    bookable: true,
  },
  {
    id: 'efferent-membrane-plasma',
    name: 'Мембранный плазмаферез',
    price: '20000 сом',
    category: 'Эфферентология',
    department: 'Плазмаферез',
    description: 'Аппаратный мембранный плазмаферез на системе Hemofenix по назначению специалиста.',
    duration: '90-120 мин',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    badge: 'Hemofenix',
    bookable: true,
  },
  {
    id: 'efferent-laser-blood',
    name: 'Лазерное облучение крови',
    price: '700 сом',
    category: 'Эфферентология',
    department: 'Плазмаферез',
    description: 'Лазерное облучение крови по назначению врача.',
    duration: '20 мин',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    bookable: true,
  },
  {
    id: 'efferent-laser-local',
    name: 'Лазерное облучение местно',
    price: '400 сом',
    category: 'Эфферентология',
    department: 'Плазмаферез',
    description: 'Местное лазерное облучение по назначению врача.',
    duration: '15 мин',
    doctorIds: ['kabylov-zhyldyzbek-saparovich'],
    bookable: true,
  },
  {
    id: 'speech-consult',
    name: 'Консультация логопеда-дефектолога',
    price: '700 сом',
    category: 'Логопед-дефектолог',
    department: 'Логопед-дефектолог',
    description: 'Первичная консультация логопеда-дефектолога.',
    duration: '30 мин',
    doctorIds: ['logoped-room'],
    bookable: true,
  },
  {
    id: 'speech-half-hour',
    name: 'Получасовое занятие',
    price: '700 сом',
    category: 'Логопед-дефектолог',
    department: 'Логопед-дефектолог',
    description: 'Индивидуальное занятие 30 минут.',
    duration: '30 мин',
    doctorIds: ['logoped-room'],
    bookable: true,
  },
  {
    id: 'speech-hour',
    name: 'Часовое занятие',
    price: '1200 сом',
    category: 'Логопед-дефектолог',
    department: 'Логопед-дефектолог',
    description: 'Индивидуальное занятие 60 минут.',
    duration: '60 мин',
    doctorIds: ['logoped-room'],
    bookable: true,
  },
  {
    id: 'speech-massage',
    name: 'Логопедический массаж',
    price: '200 сом',
    category: 'Логопед-дефектолог',
    department: 'Логопед-дефектолог',
    description: 'Логопедический массаж по назначению специалиста.',
    duration: 'По записи',
    doctorIds: ['logoped-room'],
    bookable: true,
  },
  {
    id: 'procedure-iv-drip',
    name: 'Внутривенное капельное введение',
    price: '300 сом',
    category: 'Процедурный кабинет',
    department: 'Процедурный кабинет',
    description: 'Капельное введение препарата по назначению врача.',
    duration: '30-60 мин',
    doctorIds: ['procedure-room'],
    bookable: true,
  },
  {
    id: 'procedure-iv-jet',
    name: 'Внутривенное струйное введение',
    price: '200 сом',
    category: 'Процедурный кабинет',
    department: 'Процедурный кабинет',
    description: 'Струйное внутривенное введение препарата.',
    duration: '15 мин',
    doctorIds: ['procedure-room'],
    bookable: true,
  },
  {
    id: 'procedure-im-injection',
    name: 'Внутримышечная инъекция',
    price: '100 сом',
    category: 'Процедурный кабинет',
    department: 'Процедурный кабинет',
    description: 'Внутримышечная инъекция по назначению врача.',
    duration: '10 мин',
    doctorIds: ['procedure-room'],
    bookable: true,
  },
  {
    id: 'ecg-basic',
    name: 'ЭКГ',
    price: '400 сом',
    category: 'ЭКГ',
    department: 'Кардиология',
    description: 'Электрокардиограмма.',
    duration: '15 мин',
    doctorIds: ['kabulova-gulbara-saparalievna'],
    bookable: true,
  },
];
